### ISSUE TITLE
Index for FAISS/Myscale

### ISSUE THREAD

**Issue by sdhossain** [myscale/Retrieval-QA-Benchmark#14]
Is there a process to install/build the index for FAISS or is it uploaded somewhere?

**Comment by MochiXu** [comment]
We already have the FAISS index file ready. You can download it from the provided [S3 link](https://myscale-datasets.s3.ap-southeast-1.amazonaws.com/RQA/IVFSQ_IP.index).

**Comment by chtlp** [comment]
Hi @sdhossain, we just added links for both faiss index and parquet file for inserting into MyScale. A free read-only MyScale pod is also provided for quick experimentation with the Wikipedia data. See [here](https://github.com/myscale/Retrieval-QA-Benchmark?tab=readme-ov-file#replicate-our-faiss--myscale-benchmark) for more details.
